-d C:\Users\EVA\Desktop\FPGA-Synthesizable-8Bit-CPU\fpga\gowin\FPGA-Synthesizable-8Bit-CPU\impl\gwsynthesis\FPGA-Synthesizable-8Bit-CPU.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\EVA\Desktop\FPGA-Synthesizable-8Bit-CPU\fpga\gowin\FPGA-Synthesizable-8Bit-CPU\src\tang_nano_20k.cst
-cfg C:\Users\EVA\Desktop\FPGA-Synthesizable-8Bit-CPU\fpga\gowin\FPGA-Synthesizable-8Bit-CPU\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
